version: '2.1'  
services:  
  caddy:
    build: .
    image: awesomecontainer/wdocker-caddy:${DOCKERTAG:-latest}
    container_name: caddy
    volumes:
      - C:\DockerData\caddy:c:\caddydata
    network_mode: nat
    restart: unless-stopped
    ports:
      - 80:80